author: Tamara Cook
github_url: https:://github.com/strategyc-games/hangman
# module: BoardGames
# output: docs/BoardGames
module: HangMan
output: docs/HangMan
sdk: macosx
swift_version: 4.2
min_acl: internal
# clean: true
xcodebuild_arguments:
  - "-scheme"
  - "hangman-Package"
